services:
  - type: web
    name: analise-software
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: config.ProductionConfig
      - key: PORT
        value: 10000 